# Generated by Django 5.0.6 on 2024-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedback_comment_alter_feedback_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(help_text='Type your feedback here...', verbose_name='Your Comment'),
        ),
    ]
