# Generated by Django 5.0.6 on 2024-07-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='public_key',
            field=models.TextField(blank=True, editable=False, help_text='The public key of the feedback.', null=True, verbose_name='Public Key'),
        ),
    ]
