# Generated by Django 5.0.6 on 2024-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_feedback_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='digital_signature',
            field=models.BinaryField(blank=True, help_text='The digital signature of the feedback.', null=True, verbose_name='Digital Signature'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='public_key',
            field=models.TextField(blank=True, editable=False, help_text='The public key for verifying the digital signature.', null=True, verbose_name='Public Key'),
        ),
    ]
