# Generated by Django 5.0.6 on 2024-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_feedback_digital_signature_alter_feedback_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='signature',
        ),
        migrations.AddField(
            model_name='feedback',
            name='e_signature',
            field=models.ImageField(default=1, help_text='Upload the author signature.', upload_to='media/feedbacks/signature/', verbose_name='Your Signature'),
            preserve_default=False,
        ),
    ]
