# Generated by Django 5.0.6 on 2024-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_remove_feedback_signature_feedback_e_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='e_signature',
            field=models.ImageField(help_text='Upload the author signature.', upload_to='media/feedbacks/signature/', verbose_name='E Signature'),
        ),
    ]
