# Generated by Django 5.0.6 on 2024-07-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0008_alter_feedback_e_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='e_signature',
            field=models.ImageField(help_text='Upload the author signature.', upload_to='', verbose_name='E Signature'),
        ),
    ]
