# Generated by Django 5.0.6 on 2024-07-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='e_signature',
            field=models.ImageField(default=11, help_text='Upload your signature.', upload_to='media/users/signature/', verbose_name='E Signature'),
            preserve_default=False,
        ),
    ]
